version: "3"
services:
  fastapi:
    depends_on:
      - postgres
    build: .
    ports:
      - 8000:8000
      - 5432:5432
    volumes:
      - ./:/usr/src/app
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    #env_file:
    #  - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=fastapi_socialmedia
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password123
      - SECRET_KEY=4d3bb5664dfdb52308ff7286b25fc88ac016fd808fa097107a115ba8527cf59b
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi_socialmedia
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: